# Generated by Django 5.0.1 on 2024-02-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0003_employe_signup_user_resturent_signup_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe_signup',
            name='status',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='resturent_signup',
            name='status',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
