# Generated by Django 5.0.1 on 2024-02-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0006_remove_add_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_food',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermodule.resturent_signup'),
            preserve_default=False,
        ),
    ]
