# Generated by Django 5.0.1 on 2024-02-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0008_resturent_signup_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturent_signup',
            old_name='image',
            new_name='image1',
        ),
    ]
