# Generated by Django 5.0.1 on 2024-03-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0009_rename_image_resturent_signup_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=25)),
                ('quantity', models.CharField(max_length=25)),
                ('res', models.CharField(max_length=25)),
                ('ordered', models.CharField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.resturent_signup')),
            ],
        ),
    ]
