# Generated by Django 5.0.1 on 2024-03-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0013_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=254)),
                ('cont', models.CharField(max_length=25)),
                ('mess', models.TextField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.user_signup')),
            ],
        ),
    ]
