# Generated by Django 5.0.1 on 2024-03-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0014_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='usname',
        ),
    ]
