# Generated by Django 5.0.1 on 2024-03-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0015_rename_name_feedback_usname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
